CREATE TABLE "public"."cart_activity_log" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "event_id" UUID UNIQUE NOT NULL,
    "operation_type" text NOT NULL,
    "user_id" integer NOT NULL,
    "product_id" integer NOT NULL,
    "quantity" integer NOT NULL
);
